### PR TITLE
Issue #2 Scaling on low-resolution displays

### PR DESCRIPTION
**Pull request by Ottani**
Creating the window with the desktop resolution, using 2 views, one for drawing the player and world and another one for drawing the status bar

### CODE REVIEW

**Comment by Ottani** [comment]
This should close #2

**Comment by j4cobgarby** [comment]
Nice - thanks. I can't test this at the moment, but I will soon. Could you resolve the conflicts in main.cpp? If not, I can do it fairly easily, I want to keep the window styles on the RenderWindow.

**Comment by j4cobgarby** [comment]
Okay, looks good, I've resolved the conflict now, and tested the code.

**Comment by Ottani** [comment]
Sorry, I  should've made a pull before the branch. Thanks.

**Pull request merged**
